### PR TITLE
Refactored code

### PR DESCRIPTION
**Pull request by pjebs**
- Not tested (or even compiled).
- README.md will need to change.
- GAE has a different namespacing system to standalone go apps. Can't remember which is which so you'll need to adjust appropriately.

### CODE REVIEW

**Comment by pjebs** [comment]
Ooops in `log` will need an alias to `l log` since it is the same as `"google.golang.org/appengine/log"`

**Comment by pjebs** [comment]
For change in folder structure: I was just copying this: https://github.com/golang/appengine

**Comment by pjebs** [comment]
I'll be using the logger but just keep in mind that the singleton context is not idiomatic go. It'll work find and there is nothing wrong with it. It's more 'objective-c' style that golang.

**Comment by benguild** [comment]
Yeah I'm not a fan of the singleton. By the way, this doesn't seem to work:

```
cannot use NewDebugLogger(Context(c.Request)) (type DebugLogger) as type io.Writer in argument to "log".New:
    *DebugLogger does not implement io.Writer (missing Write method)
```

**Comment by pjebs** [comment]
how are you using it?

**Comment by pjebs** [comment]
no don't use log.New

**Comment by benguild** [comment]
Oh, just call it straight?

**Comment by benguild** [comment]
Ah, I see. Sorry! :)

**Comment by pjebs** [comment]
`db.SetLogger(log.NewDebugLogger(context.Context(r)))`

**Comment by benguild** [comment]
OK, so if I put `defer context.CleanUp()` right before that, it's all good? For me, it's being called from an `DatabaseInit()` function, which returns... so wouldn't that run right as the function returns? Or would it wait until the entire request finishes? (Sorry, never run into this issue.)

**Comment by benguild** [comment]
The other place I could call it is when the handler finishes....?

**Comment by pjebs** [comment]
no - then it will  immediately get called after the function ends. You want it to get called when the request cycle ends. You'll need to create custom middleware.

But really, that singleton approach for the context is not idiomatic. It should be done like this: https://blog.golang.org/context

**Comment by benguild** [comment]
OK, that's what I thought. I can toss it in after the handler finishes. I'm sadly still learning Go (not sure if you can tell, haha) and some of these concepts are a bit foreign at the moment.

**Comment by pjebs** [comment]
if all your application logic happens in that handler, then you can place it just before the handler finishes.

**Comment by benguild** [comment]
Wait, I think I get it:

```
    r := gin.New();
    r.Use(Middleware());
```

```
func Middleware() gin.HandlerFunc {
    return func(c *gin.Context) {
        c.Next();
        GAEBridgeContext.CleanUp(c.Request);

    }

}
```

... Like this?

**Comment by pjebs** [comment]
no before c.Next() and with a defer.

**Comment by benguild** [comment]
OK, cool. I'll put that in the README!

**Comment by pjebs** [comment]
Your way at first glance appears to make sense but it misunderstands how middleware works. Any middleware up the chain may not call c.Next() (you can't guarantee it). If it doesn't, your CleanUp() won't get called. If you put it before the c.Next() and with a defer, it's guaranteed to get called.

**Comment by benguild** [comment]
Very interesting. OK, cool. Thanks for your help! Glad we were able to resolve this somehow, and I learned something new about Golang. :)

**Comment by pjebs** [comment]
Yu'll probably want to do the same pattern with your database connection.

**Comment by benguild** [comment]
Will do. :)

**Comment by pjebs** [comment]
If you're starting off, prob better to use Negroni. Far simpler than Gin-Gonic. That's my preferred middleware stack. Definitely simpler and possibly faster.

**Comment by benguild** [comment]
Just starred it. I like `gin-gonic` but will check it out.

**Comment by pjebs** [comment]
The problem with gin-gonic is its 'proprietary'  `gin.Context` interface. It is not very idiomatic since the majority of the go community uses the Handler interface: https://golang.org/pkg/net/http/#Handler as per the standard library.
It means you need to use an adapter to link code not designed for gin-gonic.
Negroni uses the Handler interface directly so you can practically use code from anywhere and with little (if any) changes plug it in.

**Comment by benguild** [comment]
Hmm, why do people like `gin-gonic` then?

**Comment by pjebs** [comment]
Negroni and Gin-Gonic are very popular.

Gin-Gonic's claim for speed is the use of httprouter.
httprouter sacrifices flexibility in the routing patterns in favour of speed.
Negroni is router-agnostic. If you need speed you can use httprouter. If you need flexibility, you can use gorrila mux. You can make some routes use httprouter and others use gorilla mux.

**Comment by benguild** [comment]
Hmm, got it. If passing the context around ends up being a bit of a disaster, I'll definitely think back to this advice. Thanks again for it.

**Comment by benguild** [comment]
Is `defer` still going to be called if the code panics? Otherwise it might leave a context in memory.

**Comment by pjebs** [comment]
it will **always** get called.

**Comment by pjebs** [comment]
That's in fact how the recovery middleware works in gin-gonic and negroni.
Go programs crash and exit the moment a panic is not recovered from.
On GAE, if the go program crashes it will kick start it again.

This is one of the most important articles to read: https://blog.golang.org/defer-panic-and-recover

**Comment by pjebs** [comment]
Did you end up trying to get the gorm caching to work?

**Comment by benguild** [comment]
I'm actually about to start messing with that right now. However, I'm sort of trying to figure out how to pass multiple database connections between various handlers, while neatly handling the cleanups.

**Comment by benguild** [comment]
Like, there's a separate read/write/search database connections and these need to be initiated on first use, and I'm trying to avoid the singleton route since that requires the cleanup. Is it better to pass these connections as closure functions or something via the context?

**Comment by pjebs** [comment]
huh?

**Comment by benguild** [comment]
Basically I have 3 database connections, and not all of them are necessary for each request, so they have to be created on demand. What I wish I could do is something like:

```
databaseWriteConnection().Exec("INSERT...");
```

... Where it would create the connection and close it automatically on request's finish.

**Comment by benguild** [comment]
Actually I think I just solved my own problem by tossing the DB stuff into a singleton like we were working with on the context in this, and putting the `CleanUp()` function call in middleware.

**Comment by pjebs** [comment]
That's the right approach. That's what I do. I copy Laravel (PHP framework) approach.
I use gorilla context to store the database object and close it from gorilla context.

**Comment by pjebs** [comment]
`databaseWriteConnection` should be a function of `r` or I suspect you're doing something wrong.

**Comment by benguild** [comment]
It's currently a singleton... but I guess one could store it within the Request itself?

**Comment by pjebs** [comment]
if it's independent of `r` then how do you know when to close it and open it?
If you are closing at at the end of request cycle using middleware, how do you know that you need to reopen it again?

**Comment by benguild** [comment]
Well, as I was saying, there are several DB connections available depending on what is needed to serve the request. Not all of them (or maybe none of them) are required for a request... for example, if everything is cached it would need no DB connections to read data. But, then maybe it needs to update a single row... so it'd connect to the write DB box. It opens the connection on first need, and... only that one (if it hadn't been opened already), not all of them. They are all "defer"'ed to be closed regardless.

**Pull request merged**
