### PR TITLE
Grouting and general concurrency protection

### PR DESCRIPTION
**Pull request by pjebs**
Untested - not currently on my development computer but should work.

### CODE REVIEW

**Comment by benguild** [comment]
So it won't free the memory without manually calling CleanUp() before the end of the request?

**Comment by pjebs** [comment]
If you are using a middleware stack like Negroni, inside the earliest middleware that calls `setLogger` you'd also call `defer gaebridge.CleanUp(r)`.

That way you never have to remember to call `CleanUp()` again because it's guaranteed to get called eventually.

Otherwise well after the request is over, the `contexts` variable will still retain the request object and the associated GAE Context  in the heap forever even though they are meaningless.

Also, it would be advised that your `contexts.go` file should be housed in a separate sub-package because its usefulness transcends just being used with `DebugLogWriter`

**Comment by benguild** [comment]
I see what you're saying. I'm using `gin-gonic`, and with several sub-handlers... so just calling `defer` probably would sidestep the whole benefit of context as it'd drop the context, right? It's supposed to be retained, just not past the end of execution.

Does App Engine not do its own cleanup?

**Comment by pjebs** [comment]
Let me just modify your code a bit.

**Comment by pjebs** [comment]
AppEngine go code is almost no different from standalone go code hence is garbage collected.
The issue is the garbage collector won't know if the request is still in use (and hence its associated context) because the package-level map variable ("global" variable) still keeps a reference to it. But after your request cycle is finished, it will still keep a reference to it even though it is meaningless. Hence you will need to delete it out yourself or it will keep it forever.

In terms of making it easier to delete it out (i.e. call `CleanUp()`), you can do it manually when you know that the request cycle is about to finish AND you know you will NEVER use `r` again or a context for anything **OR** you can make it easier by using your middleware stack automatically run the `CleanUp()` command.

All these middleware (whether its negroni or gin-gonic) libraries essentially work the same way. Occasionally you come across one that is LIFO but almost all are FIFO: https://mattstauffer.co/blog/laravel-5.0-middleware-filter-style

You can have 1 layer of middleware that gets called early create your context. Then you can `defer CleanUp(r)` knowing that `defer` is guaranteed to eventually get called. If the `defer` is early enough in your middleware stack, then you can for all practical purposes also assume that it is at the end of the request cycle.

**Comment by pjebs** [comment]
Here's a gin-gonic example: https://github.com/gin-gonic/contrib/blob/master/sessions/sessions.go#L64

In your case you can make custom middleware: https://github.com/gin-gonic/gin#custom-middleware
Before the `c.Next()` statement, just call `CleanUp()`. Make sure your custom middleware is quite early in your stack before your own application logic.

**Comment by benguild** [comment]
Are you saying to call `defer CleanUp()` and it will retain it for the remainder of the request, or will it clean up immediately when its surrounding function returns?

**Comment by pjebs** [comment]
(Using gin-gonic custom middleware example above) Say you have an early middleware that gets called before anything you do (your application logic).

By fiat, we place it early in the stack for the remainder of example.
It gets reached first before your application logic is reached.

Your application logic will get eventually get called due to the `c.Next()` statement. (i.e. all the middleware will call it until the stack reaches your application logic.

If you have the `defer` before the `c.Next()` statement (where the example says `"// before request"`), then we know that that statement will get called before `c.Next()` hence before your application logic.
**BUT** it is a defer statement hence it will _actually_ get called **AFTER** `log.Println(status)`.

But since `log.Println(status)` is called **AFTER** `c.Next()`, we know your application logic is completed and the request cycle is about to end. As the middleware unwinds, it will eventually execute the `CleanUp()` (which was deferred), hence it will automatically cleanup the request object and associated Context object which was stored in the global map and is no longer necessary.

**Comment by pjebs** [comment]
Anyway let me know if you have any other questions. Also let me know if you will adopt the pull request so I can delete out my fork.

**Comment by benguild** [comment]
For sure, just grabbing dinner and I'll check it out tonight.

**Pull request merged**
